server:
  port: 9001

spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    #向sentinel控制台注册服务
    sentinel:
      transport:
        dashboard: localhost:8080
      #取消控制台懒加载
      eager: true
      # 流控规则持久化到nacos
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#feign.sentinel.enabled=true
feign:
  sentinel:
    enabled: true


#消费者将要去访问的微服务名称（成功注册进nacos的微服务提供者），在这配置了访问的服务，业务类就不用在定义常量了
service-url:
  nacos-user-service: http://user

